import React, { createContext, useContext, useState, useEffect } from 'react';

const dict = {
  en: {
    // Nav
    adbTools: 'ADB Tools',
    inspector: 'Inspector',
    simulator: 'Simulator C2C',
    signer: 'APK Signer',
    settings: 'Settings',
    connected: 'Connected',
    systemLogs: 'SYSTEM LOGS',
    clear: 'Clear',
    title: 'ISV Web Toolkit',
    confirmAction: 'Confirm Action',
    removeApkQuestion: 'Remove analyzed APK?',
    removeApkDesc: 'All current analysis data will be deleted and you must upload the file again.',
    yesRemove: 'Yes, Remove',
    cancel: 'Cancel',
    signOut: 'Sign Out',
    removeApk: 'Remove APK',
    changePassword: 'Change Password',
    guest: 'Guest',
    staff: 'STAFF',
    developer: 'DEVELOPER',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    passwordSecurityDesc: 'Secure your account with a high-security new password.',
    passwordLogoutDesc: 'Once updated, you will be logged out of all other devices for security.',
    
    // Inspector
    apkInspector: 'APK Inspector',
    selectApk: 'SELECT APK',
    readyInspect: 'Ready to Inspect',
    uploadApkDesc: 'Upload an APK to view package details, permissions, SDK versions, and security status.',
    versionName: 'Version Name',
    versionCode: 'Version Code',
    minSdk: 'Min SDK',
    targetSdk: 'Target SDK',
    debuggable: 'Debuggable',
    signatureVerif: 'Signature Verification',
    permissions: 'Permissions',
    installApk: 'INSTALL APK',
    verLogCompleto: 'View full apksigner log',
    unknownApp: 'Unknown Application',
    readingApk: 'Reading APK manifest and signatures...',
    uninstall: 'UNINSTALL',
    
    // Logcat
    logcatViewer: 'Logcat',
    download: 'Download',
    refresh: 'Refresh',
    clearUi: 'Clear UI',
    noLogcatData: 'No logcat data. Click refresh to fetch.',
    filterPackage: 'Filter by Package...',
    allPackages: 'All Packages',
    
    // Simulator
    paymentSimulator: 'Simulator Cloud to Cloud',
    history: 'History',
    saveCommand: 'Save Command',
    btnSend: 'SEND',
    bodyField: 'Body',
    quickParams: 'Quick Params',
    amount: 'Amount',
    env: 'Environment',
    getToken: 'Get Token',
    simSubtitle: 'Test and debug Integrated POS transactions in real-time.',
    uat: 'UAT (SANDBOX)',
    production: 'PRODUCTION',
    envTitle: 'ENVIRONMENT',
    historyTitle: 'RECENT HISTORY',
    quickActions: 'QUICK ACTIONS',
    clientId: 'Client ID',
    clientSecret: 'Client Secret',
    fetchingToken: 'Fetching Access Token...',
    tokenSuccess: 'Token obtained successfully',
    tokenError: 'Error fetching token',
    showSecret: 'Show Secret',
    hideSecret: 'Hide Secret',
    
    // Signer
    apkSignerPro: 'APK Signer Pro',
    dragDropSign: 'Drag and drop your .apk file here to sign with default or custom keys.',
    selectApkFile: 'Select APK File',
    requiredInsights: 'Upload an APK in the Inspector view first to use the signer tools.',
    uploadJks: 'Upload JKS',
    createSignature: 'Create Signature',
    signApk: 'Sign APK',
    targetApk: 'Target APK',
    signApkTitle: 'Sign APK Application',
    jksGeneratorTitle: 'JKS Signature Generator',
    
    // Auth
    accessSystem: 'Access System',
    bsearch: 'Searching...',
    disconnected: 'Disconnected',
    none: 'None',

    // Login
    loginWelcome: 'Welcome Back',
    loginSubtitle: 'The all-in-one suite for ISV developers and QA engineers. Streamline your Android workflow today.',
    email: 'Email Address',
    password: 'Password',
    signIn: 'Sign In',
    orContinueWith: 'Or continue with',
    google: 'Google',
    microsoft: 'Microsoft',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don\'t have an account?',
    contactSupport: 'Contact Support',
    loginError: 'Invalid credentials. Please try again.',
    tagline: 'Empowering Innovation',

    // Register & Forgot
    createAccount: 'Create Account',
    registerSubtitle: 'Join the ISV Web Toolkit community and start optimizing your workflow.',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    registerBtn: 'Get Started',
    alreadyHaveAccount: 'Already have an account?',
    resetPassword: 'Reset Password',
    forgotSubtitle: 'Enter your email and we\'ll send you instructions to reset your password.',
    sendInstructions: 'Send Instructions',
    backToLogin: 'Back to Login',
    emailSent: 'Email Sent!',
    emailSentDesc: 'Please check your inbox for the confirmation link.',
    passwordChanged: 'Password Changed Successfully',
    yes: 'YES',
    no: 'NO',
    valid: 'VALID',
    invalid: 'INVALID',
    certificate: 'Certificate',
    sha256: 'SHA-256',
    signatureScheme: 'Signature',
    signatureValid: 'VALID SIGNATURE',
    signatureInvalid: 'INVALID SIGNATURE'
  },
  es: {
    adbTools: 'Herramientas ADB',
    inspector: 'Inspector',
    simulator: 'Simulador C2C',
    signer: 'Firma JKS',
    settings: 'Ajustes',
    connected: 'Conectado',
    systemLogs: 'REGISTROS',
    clear: 'Limpiar',
    title: 'ISV Web Toolkit',
    confirmAction: 'Confirmar Acción',
    removeApkQuestion: '¿Quitar APK analizada?',
    removeApkDesc: 'Se borrarán todos los datos del análisis actual y deberás subir el archivo nuevamente.',
    yesRemove: 'Sí, Quitar',
    cancel: 'Cancelar',
    signOut: 'Cerrar Sesión',
    removeApk: 'Quitar APK',
    changePassword: 'Cambiar Contraseña',
    guest: 'Invitado',
    staff: 'EQUIPO',
    developer: 'DESARROLLADOR',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmNewPassword: 'Confirmar Nueva Contraseña',
    updatePassword: 'Actualizar Contraseña',
    passwordSecurityDesc: 'Asegura tu cuenta con una nueva contraseña de alta seguridad.',
    passwordLogoutDesc: 'Una vez actualizada, serás desconectado de todos los demás dispositivos por seguridad.',
    
    apkInspector: 'Inspector APK',
    selectApk: 'SELECCIONAR APK',
    readyInspect: 'Listo para Inspeccionar',
    uploadApkDesc: 'Sube un APK para ver detalles del paquete, permisos, versiones SDK y estado de seguridad.',
    versionName: 'Nombre Versión',
    versionCode: 'Código Versión',
    minSdk: 'SDK Mínimo',
    targetSdk: 'SDK Objetivo',
    debuggable: 'Debuggable',
    signatureVerif: 'Verificación de Firma',
    permissions: 'Permisos',
    installApk: 'INSTALAR APK',
    verLogCompleto: 'Ver Log Completo de apksigner',
    unknownApp: 'Aplicación Desconocida',
    readingApk: 'Leyendo manifiesto y firmas del APK...',
    uninstall: 'DESINSTALAR',
    
    logcatViewer: 'Logcat',
    download: 'Descargar',
    refresh: 'Refrescar',
    clearUi: 'Limpiar Interfaz',
    noLogcatData: 'Sin datos. Haz clic en Refrescar.',
    filterPackage: 'Filtrar Paquete...',
    allPackages: 'Todos los Paquetes',
    
    paymentSimulator: 'Simulador Cloud to Cloud',
    history: 'Historial',
    saveCommand: 'Guardar',
    btnSend: 'ENVIAR',
    bodyField: 'Cuerpo',
    quickParams: 'Parámetros',
    amount: 'Monto',
    env: 'Entorno',
    getToken: 'Obtener Token',
    simSubtitle: 'Prueba y depura transacciones de POS Integrado en tiempo real.',
    uat: 'UAT (SANDBOX)',
    production: 'PRODUCCIÓN',
    envTitle: 'ENTORNO',
    historyTitle: 'HISTORIAL RECIENTE',
    quickActions: 'ACCIONES RÁPIDAS',
    clientId: 'Client ID',
    clientSecret: 'Client Secret',
    fetchingToken: 'Obteniendo Token de Acceso...',
    tokenSuccess: 'Token obtenido con éxito',
    tokenError: 'Error al obtener el token',
    showSecret: 'Mostrar Secreto',
    hideSecret: 'Ocultar Secreto',
    
    apkSignerPro: 'Firmador APK',
    dragDropSign: 'Arrastra tu .apk aquí para firmar con llaves por defecto o personalizadas.',
    selectApkFile: 'Seleccionar Archivo APK',
    requiredInsights: 'Primero inspecciona un archivo APK en el Inspector para habilitar la firma.',
    uploadJks: 'Subir JKS',
    createSignature: 'Crear Firma',
    signApk: 'Firmar APK',
    targetApk: 'APK de Destino',
    signApkTitle: 'Firmar Aplicación APK',
    jksGeneratorTitle: 'Generador de Firma JKS',
    
    accessSystem: 'Acceder',
    bsearch: 'Buscando...',
    disconnected: 'Desconectado',
    none: 'Ninguno',

    // Login
    loginWelcome: 'Bienvenido de Nuevo',
    loginSubtitle: 'La suite integral para desarrolladores ISV y QA. Optimiza tu flujo de trabajo Android hoy mismo.',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    signIn: 'Iniciar Sesión',
    orContinueWith: 'O continúa con',
    google: 'Google',
    microsoft: 'Microsoft',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta?',
    contactSupport: 'Contactar Soporte',
    loginError: 'Credenciales inválidas. Inténtalo de nuevo.',
    tagline: 'Potenciando la Innovación',

    // Register & Forgot
    createAccount: 'Crear Cuenta',
    registerSubtitle: 'Únete a la comunidad ISV Web Toolkit y comienza a optimizar tu flujo.',
    fullName: 'Nombre Completo',
    confirmPassword: 'Confirmar Contraseña',
    registerBtn: 'Empezar ahora',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    resetPassword: 'Restablecer Contraseña',
    forgotSubtitle: 'Ingresa tu correo y te enviaremos instrucciones para restablecer tu clave.',
    sendInstructions: 'Enviar Instrucciones',
    backToLogin: 'Volver al Login',
    emailSent: '¡Correo Enviado!',
    emailSentDesc: 'Por favor revisa tu bandeja de entrada para el enlace de confirmación.',
    passwordChanged: 'Contraseña Cambiada con Éxito',
    yes: 'SÍ',
    no: 'NO',
    valid: 'VÁLIDA',
    invalid: 'INVÁLIDA',
    certificate: 'Certificado',
    sha256: 'SHA-256',
    signatureScheme: 'Firma',
    signatureValid: 'FIRMA VÁLIDA',
    signatureInvalid: 'FIRMA INVÁLIDA'
  },
  pt: {
    adbTools: 'Ferramentas ADB',
    inspector: 'Inspetor',
    simulator: 'Simulador C2C',
    signer: 'Assinador APK',
    settings: 'Configurações',
    connected: 'Conectado',
    systemLogs: 'LOGS DO SISTEMA',
    clear: 'Limpar',
    title: 'ISV Web Toolkit',
    confirmAction: 'Confirmar Ação',
    removeApkQuestion: 'Remover APK analisada?',
    removeApkDesc: 'Todos os dados da análise atual serão excluídos e você deverá carregar o arquivo novamente.',
    yesRemove: 'Sim, Remover',
    cancel: 'Cancelar',
    signOut: 'Sair',
    removeApk: 'Remover APK',
    changePassword: 'Alterar Senha',
    guest: 'Convidado',
    staff: 'EQUIPE',
    developer: 'DESENVOLVEDOR',
    currentPassword: 'Senha Atual',
    newPassword: 'Nova Senha',
    confirmNewPassword: 'Confirmar Nova Senha',
    updatePassword: 'Atualizar Senha',
    passwordSecurityDesc: 'Proteja sua conta com uma nova senha de alta segurança.',
    passwordLogoutDesc: 'Uma vez atualizada, você será desconectado de todos os outros dispositivos por segurança.',
    
    apkInspector: 'Inspetor APK',
    selectApk: 'SELECIONAR APK',
    readyInspect: 'Pronto para Inspecionar',
    uploadApkDesc: 'Faça upload de um APK para ver os detalhes do pacote, permissões, versões SDK e o estado de segurança.',
    versionName: 'Nome da Versão',
    versionCode: 'Código da Versão',
    minSdk: 'SDK Mínimo',
    targetSdk: 'SDK Alvo',
    debuggable: 'Depurável',
    signatureVerif: 'Verificação de Assinatura',
    permissions: 'Permissões',
    installApk: 'INSTALAR APK',
    verLogCompleto: 'Ver logo completo do apksigner',
    unknownApp: 'Aplicativo Desconhecido',
    readingApk: 'Lendo manifesto e assinaturas do APK...',
    uninstall: 'DESINSTALAR',
    
    logcatViewer: 'Logcat',
    download: 'Baixar',
    refresh: 'Atualizar',
    clearUi: 'Limpar Tela',
    noLogcatData: 'Sem dados. Clique em Atualizar.',
    filterPackage: 'Filtrar Pacote...',
    allPackages: 'Todos os Pacotes',
    
    paymentSimulator: 'Simulador Cloud to Cloud',
    history: 'Histórico',
    saveCommand: 'Salvar',
    btnSend: 'ENVIAR',
    bodyField: 'Corpo',
    quickParams: 'Parâmetros',
    amount: 'Montante',
    env: 'Ambiente',
    getToken: 'Obter Token',
    simSubtitle: 'Teste e depure transações de POS Integrado em tempo real.',
    uat: 'UAT (SANDBOX)',
    production: 'PRODUÇÃO',
    envTitle: 'AMBIENTE',
    historyTitle: 'HISTÓRICO RECENTE',
    quickActions: 'AÇÕES RÁPIDAS',
    clientId: 'Client ID',
    clientSecret: 'Client Secret',
    fetchingToken: 'Obtendo Token de Acesso...',
    tokenSuccess: 'Token obtido com sucesso',
    tokenError: 'Erro ao obter o token',
    showSecret: 'Mostrar Segredo',
    hideSecret: 'Ocultar Segredo',
    
    apkSignerPro: 'Assinador APK Pro',
    dragDropSign: 'Arraste seu .apk aqui para assinar com chaves padrão ou customizadas.',
    selectApkFile: 'Selecionar Arquivo APK',
    requiredInsights: 'Primeiro inspecione um arquivo APK no Inspetor para habilitar a assinatura.',
    uploadJks: 'Carregar JKS',
    createSignature: 'Criar Assinatura',
    signApk: 'Assinar APK',
    targetApk: 'APK de Destino',
    signApkTitle: 'Assinar Aplicativo APK',
    jksGeneratorTitle: 'Gerador de Assinatura JKS',
    
    accessSystem: 'Acessar',
    bsearch: 'Procurando...',
    disconnected: 'Desconectado',
    none: 'Nenhum',

    // Login
    loginWelcome: 'Bem-vindo de Volta',
    loginSubtitle: 'A suíte completa para desenvolvedores ISV e engenheiros de QA. Otimize seu fluxo Android hoje.',
    email: 'E-mail',
    password: 'Senha',
    signIn: 'Entrar',
    orContinueWith: 'Ou continue com',
    google: 'Google',
    microsoft: 'Microsoft',
    forgotPassword: 'Esqueceu a senha?',
    noAccount: 'Não tem uma conta?',
    contactSupport: 'Contatar Suporte',
    loginError: 'Credenciais inválidas. Tente novamente.',
    tagline: 'Impulsionando a Inovação',

    // Register & Forgot
    createAccount: 'Criar Conta',
    registerSubtitle: 'Junte-se à comunidade ISV Web Toolkit e comece a otimizar seu fluxo.',
    fullName: 'Nome Completo',
    confirmPassword: 'Confirmar Senha',
    registerBtn: 'Começar Agora',
    alreadyHaveAccount: 'Já tem uma conta?',
    resetPassword: 'Redefinir Senha',
    forgotSubtitle: 'Digite seu e-mail e enviaremos instruções para redefinir sua senha.',
    sendInstructions: 'Enviar Instruções',
    backToLogin: 'Voltar ao Login',
    emailSent: 'E-mail Enviado!',
    emailSentDesc: 'Verifique sua caixa de entrada para o link de confirmação.',
    passwordChanged: 'Senha Alterada com Sucesso',
    signatureValid: 'ASSINATURA VÁLIDA',
    signatureInvalid: 'ASSINATURA INVÁLIDA'
  }
};

const LangContext = createContext();

// eslint-disable-next-line react-refresh/only-export-components
export const useLang = () => useContext(LangContext);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('isv_lang') || 'es');
  const [theme, setTheme] = useState(() => localStorage.getItem('isv_theme') || 'light');

  useEffect(() => {
    localStorage.setItem('isv_lang', lang);
  }, [lang]);

  useEffect(() => {
    localStorage.setItem('isv_theme', theme);
    if (theme === 'light') {
      document.documentElement.classList.add('light');
    } else {
      document.documentElement.classList.remove('light');
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => (prev === 'dark' ? 'light' : 'dark'));
  };

  const t = (key) => dict[lang]?.[key] || key;

  return (
    <LangContext.Provider value={{ lang, setLang, theme, toggleTheme, t }}>
      {children}
    </LangContext.Provider>
  );
};
